Rocinante/Models/Job.cs
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Rocinante.Models
{
    public class Job
    {
        [Key]
        public string Id { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Id")]
        public string JobId { get; set; }
        [Display(Name = "Job Title")]
        public string Title { get; set; }
        public string Location { get; set; }
        public string Snippet { get; set; }
        public string Link { get; set; }
        public string Company { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Saved Date")]
        public DateTime SavedDate { get; set; }
        [Display(Name = "Posted")]
        public string Updated { get; set; }
        [Display(Name = "Job status")]
        public string Result { get; set; }
        [ForeignKey("IdentityUser")]
        public string UserId { get; set; }
        public virtual ICollection<Activity> activities { get; set; } = new List<Activity>();
        public Job()
        {
        }

        public Job(JToken t)
        {
            this.SavedDate = DateTime.Now;
            this.Result = "Saved";
            this.JobId = t["id"].ToString();
            this.Title = t["title"].ToString();
            this.Location = t["location"].ToString();
            this.Snippet = t["snippet"].ToString();
            this.Link = t["link"].ToString();
            this.Company = t["company"].ToString();
            this.Updated = t["updated"].ToString();
        }
    }
}

Rocinante/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rocinante.Data;
using Rocinante.Models;

namespace Rocinante.Controllers
{
    public class JobsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JobsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Jobs
        [Authorize]
        public IActionResult Index()
        {
            var loggedInUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var jobList = _context.Job.Where(x => x.UserId == loggedInUser);

            return View(jobList);
        }


        public IActionResult AddActivity(string id)
        {
            ViewData["JobId"] = id;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddActivity([Bind("ActivityDate,Action,Comment,JobId")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                _context.Add(activity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["JobId"] = new SelectList(_context.Job, "Id", "Id", activity.JobId);
            //return View(activity);
            return View();
        }
        // GET: Jobs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job.Include( y => y.activities)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // GET: Jobs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,JobId,Title,Location,Snippet,Link,Company,Updated,ContactPerson,ApplicationMethod,DateOfApplication,FollowUpDate,CompanyWebsite,WhoDoYouKnowHere,Result,UserId")] Job job)
        {
            if (ModelState.IsValid)
            {
                _context.Add(job);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(job);
        }

        // GET: Jobs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,JobId,Title,Location,Snippet,Link,Company,Updated,ContactPerson,ApplicationMethod,DateOfApplication,FollowUpDate,CompanyWebsite,WhoDoYouKnowHere,Result,UserId")] Job job)
        {
            if (id != job.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(job);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobExists(job.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(job);
        }

        // GET: Jobs/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var job = await _context.Job.FindAsync(id);
            _context.Job.Remove(job);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JobExists(string id)
        {
            return _context.Job.Any(e => e.Id == id);
        }
    }
}

Rocinante/Views/Jobs/AddActivity.cshtml
@model Rocinante.Models.Activity

@{
    ViewData["Title"] = "AddActivity";
}

<h1>AddActivity</h1>

<h4>Activity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddActivity">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ActivityDate" class="control-label"></label>
                <input type="date" asp-for="ActivityDate" class="form-control" />
                <span asp-validation-for="ActivityDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Action" class="control-label"></label>
                <select asp-for="Action" class="form-control">
                    <option value="Applied">Applied</option>
                    <option value="Interview">Phone Interview</option>
                    <option value="In-person Interview">In-person Interview</option>
                    <option value="Additional Interview">Additional Interview</option>
                    <option value="Hired">Hired</option>
                    <option value="Not Hired">Not Hired</option>
                </select>
                <span asp-validation-for="Action" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <textarea asp-for="Comment" class="form-control"></textarea>
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" value="@ViewBag.JobId" asp-for="JobId" name="JobId">
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rocinante/Views/Jobs/Create.cshtml
@model Rocinante.Models.Job

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Job</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JobId" class="control-label"></label>
                <input asp-for="JobId" class="form-control" />
                <span asp-validation-for="JobId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Snippet" class="control-label"></label>
                <input asp-for="Snippet" class="form-control" />
                <span asp-validation-for="Snippet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Company" class="control-label"></label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SavedDate" class="control-label"></label>
                <input asp-for="SavedDate" class="form-control" />
                <span asp-validation-for="SavedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Updated" class="control-label"></label>
                <input asp-for="Updated" class="form-control" />
                <span asp-validation-for="Updated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Result" class="control-label"></label>
                <input asp-for="Result" class="form-control" />
                <span asp-validation-for="Result" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rocinante/Views/Jobs/Delete.cshtml
@model Rocinante.Models.Job

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JobId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JobId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Snippet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Snippet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SavedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SavedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Updated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Updated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Result)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Result)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Rocinante/Views/Jobs/Details.cshtml
@model Rocinante.Models.Job

@{
    ViewData["Title"] = "Details";
}

    <h1>@Html.DisplayFor(model => model.Company)</h1>

<div>
    <h3>@Html.DisplayFor(model => model.Title)</h3>
    <hr />
    <dl class="row">                
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>       
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SavedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SavedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Updated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Updated)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Result)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Result)
        </dd>
        
    </dl>
</div>
<h3>Activities</h3>
<a class="btn btn-success" asp-action="AddActivity" asp-controller="Jobs" asp-route-id="@Model.Id">Add Activity</a>

<table>
    <tr>
        <th>Date</th>
        <th>Action</th>
        <th>Comment</th>

    </tr>
    @foreach (var item in Model.activities)
    {
        <tr>
            <td>@item.ActivityDate | </td> 
            <td>@item.Action | </td> 
            <td>@item.Comment</td>
        </tr>
    }
</table>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    <a asp-action="Index" asp-controller="Activities" asp-route-id="@Model.Id">Vew activities</a>
    <a asp-action="Index">Back to List</a>
</div>

Rocinante/Views/Jobs/Edit.cshtml
@model Rocinante.Models.Job

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Job</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="JobId" class="control-label"></label>
                <input asp-for="JobId" class="form-control" />
                <span asp-validation-for="JobId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Snippet" class="control-label"></label>
                <input asp-for="Snippet" class="form-control" />
                <span asp-validation-for="Snippet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Company" class="control-label"></label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SavedDate" class="control-label"></label>
                <input asp-for="SavedDate" class="form-control" />
                <span asp-validation-for="SavedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Updated" class="control-label"></label>
                <input asp-for="Updated" class="form-control" />
                <span asp-validation-for="Updated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Result" class="control-label"></label>
                <input asp-for="Result" class="form-control" />
                <span asp-validation-for="Result" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rocinante/Views/Jobs/Index.cshtml
@model IEnumerable<Rocinante.Models.Job>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">My jobs</h1>

@*<p>
        <a asp-action="Create">Create New</a>
    @Html.DisplayFor(modelItem => item.SavedDate)
    </p>*@

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class=" col-xs-12 col-sm-12 col-md-6 col-lg-4">
                <div class="card-group shadow" style="width: 20rem">
                    <div class="card-body">
                        <h5 class="card-title"><a href="@item.Link)">@item.Title</a></h5>
                        <p>@item.Company</p>
                        <p class="card-text">@Html.Raw(item.Snippet)</p>
                        <p><small class="text-muted">@item.Location</small></p>
                        <p><small class="text-muted">@item.SavedDate</small></p>
                        @{
                            var days = int.Parse(DateTime.Now.Subtract(Convert.ToDateTime(@item.Updated)).Days.ToString());
                            if (days == 0)
                            {
                                <p><small class="text-muted">Posted  To day</small></p>
                            }
                            else if (days == 1)
                            {
                                <p><small class="text-muted">Posted yesterday</small></p>
                            }
                            else if (days >= 31)
                            {
                                <p><small class="text-muted">Posted +31 days ago</small></p>
                            }
                            else
                            {
                                <p><small class="text-muted">Posted  @days days ago</small></p>
                            }
                        }

                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Edit</a>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Details</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-primary">Delete</a>
                    </div>
                </div>

            </div>



        }

    </div>
    <div class="clearfix visible-md"></div>
</div>